### ISSUE TITLE
Allow users using domains they already own, in addition to registering a new one

### ISSUE THREAD

**Issue by jwst9** [polymorpher/otc-country#10]
From @polymorpher on July 3, 2024 via Telegram:

> we need to allow users to use domains they already own, instead of forcing them to register a new one
> 
> To do this, modify createOffer at https://github.com/polymorpher/otc-country/blob/c47d362b47a932ccc508e36986953c6b9e8e0cbf/contract/contracts/OTC.sol#L155 , check if owner of domainName_ is already domainOwner_ (by calling DC contract's ownerOf https://github.com/polymorpher/dot-country/blob/14dc510dd9a354826b23f21aced3eb26ee5bba93/contracts/contracts/DC.sol#L191 ). If so, skip the web3 domain purchasing logic in the next few lines. In frontend, also check if domain is already owned, and if so, display a (green) message showing that they already own the domain, instead of the purchasing price

**Comment by polymorpher** [comment]
This is not covered by #14

**Comment by 0xvgd** [comment]
- OTC.createOffer

Come to think it again, I don't think this is right.
https://github.com/polymorpher/otc-country/blob/main/contract/contracts/OTC.sol#L242-L244

Should be the following instead?

```Solidity
if (domainContract.ownerOf(domainName_) == domainOwner_) {
  uint256 price = domainContract.getPrice(domainName_);
  bytes32 commitment = domainContract.makeCommitment(domainName_, domainOwner_, secret_);

  domainContract.commit(commitment);
  domainContract.register{value: price}(domainName_, domainOwner_, secret_);
}
```

**Comment by polymorpher** [comment]
If domain is already owned by domainOwner, there is no need to calculate price, commit, or register the domain. Just go forward with offer deployment

**Comment by 0xvgd** [comment]
Sorry typo, should be `!=`, yes
