### ISSUE TITLE
Page showing recently created offers (last 1h, 24h, 7d, 30d), accepted offers, and filter them by assets

### ISSUE THREAD

**Issue by jwst9** [polymorpher/otc-country#11]
From @polymorpher on July 3, 2024 via Telegram:

> 
> we need to have a page to show recently created offers (last 1h, 24h, 7d, 30d), accepted offers, and filter them by assets
> 
> You can do the filtering in frontend to keep it simple. But we also need a backend to index all these data. You can do a subgraph definition and have the subgraph node to monitor offer events, and inserts offers into Google Datastore or a postgres database. Then do a simple backend server that allows unauthenticated lookups based on duration or filter criteria). Or instead of doing subgraph, just have the backend to listen to contract events, and have a script that scans from block X to Y for all such events and insert missing entries to database (make sure no duplicate is inserted)

**Comment by 0xvgd** [comment]
How about querying onchain events directly from the frontend instead of backend & db?
and cache the result in local storage

**Comment by polymorpher** [comment]
You can't query events from nodes for longer than 1024 blocks, which is less than 1 hour

**Comment by 0xvgd** [comment]
Sorry, I was able to query events 18 days ago using viem's createContractEventFilter.
I think it's technically feasible to query events as much long as we want because events are stored on blocks

**Comment by polymorpher** [comment]
Each query can't span more than 1024 blocks, it is hard coded in RPC node code. Frontend would have to do over a thousand queries to get latest data without a backend index

**Comment by 0xvgd** [comment]
You are right. I can't know how long ago we have to query the block following my approach.

**Comment by 0xvgd** [comment]
Can you invite me to your google datastore?

**Comment by 0xvgd** [comment]
show offer details when clicking it?

**Comment by polymorpher** [comment]
Clickable link (new window) to the domain

**Comment by 0xvgd** [comment]
What should each event (created and accepted) show before clicking?

**Comment by polymorpher** [comment]
Source and destination asset, source amount, accept amount, exchange rate (based on current price), domain name, creation time, age

**Comment by 0xvgd** [comment]
Should accepted offer show exchange rate based on the rate at the time of accepted? (instead of current price)

**Comment by polymorpher** [comment]
Yes. Show both if possible

**Comment by 0xvgd** [comment]
It's hard to achieve pagination using gcp datastore / firestore as it doesn't fully support limit and "or where"
How about switching to supabase (postgres)?

**Comment by polymorpher** [comment]
Postgres is fine.

Datastore limit query is https://cloud.google.com/datastore/docs/samples/datastore-limit#datastore_limit-nodejs . It also supports cursor and scan

`where` is by using filter, see https://github.com/polymorpher/sms-wallet/blob/e2c089e88b90cad226bc4389b8db5186e16e4bb2/server/src/data/generic.ts#L37 and related code for example.
