### ISSUE TITLE
OTC with AccessControl

### ISSUE THREAD

**Issue by jwst9** [polymorpher/otc-country#8]
From @polymorpher on July 3, 2024 via Telegram:

> make OTC.sol with AccessControl, instead of Ownable
> 
> Have "OPERATOR" role in addition to the default admin role.  In deploy script, allow specifcying two separate accounts for transfer of the operator and admin roles. The operator role should be able to do everything the current "owner" can do

**Comment by 0xvgd** [comment]
What is the difference admin vs operator?

**Comment by polymorpher** [comment]
Admin can change revenue account and operator. Operator can't

**Comment by 0xWormh0le** [comment]
Does current OTC have admin? I can't see it

**Comment by polymorpher** [comment]
It only has an Owner, which is the deploying account

**Comment by 0xvgd** [comment]
> Admin can change revenue account and operator. Operator can't

What can't operator do?

**Comment by polymorpher** [comment]
Operator can't change revenue account or grant operator role to others

**Comment by 0xvgd** [comment]
Can admin specify protocol %?

**Comment by polymorpher** [comment]
Yes. And Operator should be able to pause the contract

**Comment by 0xvgd** [comment]
Can admin pause too?

**Comment by polymorpher** [comment]
Admin can do everything Operator can do because it can grant operator roles to any account
