### ISSUE TITLE
Add protocol fee percentage and revenue account fields to OTC contract

### ISSUE THREAD

**Issue by jwst9** [polymorpher/otc-country#9]
From @polymorpher on July 3, 2024 via Telegram:

> add protocol fee %, and revenue account fields to OTC contract
> 
> When offer is accepted, fees should be automatically paid (using dest asset) to revenue account. Protocol fee % can be set by operator. Revenue account can only be set by admin. Allow these two fields to be specified in deploy script

**Comment by 0xvgd** [comment]
Just to confirm, will the accept amount go to
- revenue (protocol fee %) to revenue account
- commission to domain owner
- rest to depositor??

**Comment by polymorpher** [comment]
yes
